version: "3.7"
networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.1.0/24
services:
  web-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./:/var/www/html"
    ports:
      - "8000:80"
    networks:
      frontend:
        ipv4_address: 172.20.1.7
